
const translations = {
    fr: {
        badge: "🚀 Lancement prévu : Mars 2026",
        title: "Arrête de procrastiner.<br>Commence à accomplir.",
        subtitle: "La première app de gestion de tâches qui s'adapte à ton énergie, tes dépendances et tes vrais objectifs. Pas juste une liste interminable.",
        emailPlaceholder: "Entre ton email...",
        cta: "Obtenir l'accès anticipé",
        successMessage: "✓ Merci ! Tu es sur la liste. On te contacte bientôt.",
        socialProof: "personnes ont déjà rejoint",
        problemTag: "Le Problème",
        problemTitle: "Les apps de tâches actuelles ignorent la réalité",
        problemSubtitle: "Elles te disent QUOI faire, mais pas COMMENT le faire en fonction de ton état réel.",
        featuresTag: "La Solution",
        featuresTitle: "ContextFlow comprend comment tu travailles vraiment",
        featuresSubtitle: "Six fonctionnalités que tu ne trouveras nulle part ailleurs",
        howItWorksTag: "Comment ça marche",
        howItWorksTitle: "En 3 étapes simples",
        comparisonTag: "Comparaison",
        comparisonTitle: "ContextFlow vs. Les Autres",
        pricingTag: "Prix",
        pricingTitle: "Choisis ton plan",
        pricingSubtitle: "Commence gratuitement. Upgrade quand tu veux.",
        faqTag: "FAQ",
        faqTitle: "Questions fréquentes",
        finalCtaTitle: "Prêt à arrêter de procrastiner ?",
        finalCtaSubtitle: "Rejoins les {count}+ personnes qui attendent ContextFlow",
        finalCtaBenefits: "✓ Accès anticipé en Février 2026 • ✓ 50% de réduction à vie • ✓ Pas de carte requise",
        copyright: "© 2026 ContextFlow. Tous droits réservés."
    },
    
    en: {
        badge: "🚀 Launch planned: March 2026",
        title: "Stop procrastinating.<br>Start accomplishing.",
        subtitle: "The first task management app that adapts to your energy, your dependencies and your real goals. Not just an endless list.",
        emailPlaceholder: "Enter your email...",
        cta: "Get early access",
        successMessage: "✓ Thanks! You're on the list. We'll contact you soon.",
        socialProof: "people already joined",
        problemTag: "The Problem",
        problemTitle: "Current task apps ignore reality",
        problemSubtitle: "They tell you WHAT to do, but not HOW to do it based on your actual state.",
        featuresTag: "The Solution",
        featuresTitle: "ContextFlow understands how you actually work",
        featuresSubtitle: "Six features you won't find anywhere else",
        howItWorksTag: "How it works",
        howItWorksTitle: "In 3 simple steps",
        comparisonTag: "Comparison",
        comparisonTitle: "ContextFlow vs. Others",
        pricingTag: "Pricing",
        pricingTitle: "Choose your plan",
        pricingSubtitle: "Start for free. Upgrade when you want.",
        faqTag: "FAQ",
        faqTitle: "Frequently asked questions",
        finalCtaTitle: "Ready to stop procrastinating?",
        finalCtaSubtitle: "Join {count}+ people waiting for ContextFlow",
        finalCtaBenefits: "✓ Early access February 2026 • ✓ 50% lifetime discount • ✓ No card required",
        copyright: "© 2026 ContextFlow. All rights reserved."
    },
    
    es: {
        badge: "🚀 Lanzamiento previsto: Marzo 2026",
        title: "Deja de procrastinar.<br>Comienza a lograr.",
        subtitle: "La primera app de gestión de tareas que se adapta a tu energía, tus dependencias y tus objetivos reales. No solo una lista interminable.",
        emailPlaceholder: "Ingresa tu correo...",
        cta: "Obtener acceso anticipado",
        successMessage: "✓ ¡Gracias! Estás en la lista. Te contactaremos pronto.",
        socialProof: "personas ya se unieron",
        problemTag: "El Problema",
        problemTitle: "Las apps de tareas actuales ignoran la realidad",
        problemSubtitle: "Te dicen QUÉ hacer, pero no CÓMO hacerlo según tu estado real.",
        featuresTag: "La Solución",
        featuresTitle: "ContextFlow entiende cómo trabajas realmente",
        featuresSubtitle: "Seis funcionalidades que no encontrarás en ningún otro lugar",
        howItWorksTag: "Cómo funciona",
        howItWorksTitle: "En 3 pasos simples",
        comparisonTag: "Comparación",
        comparisonTitle: "ContextFlow vs. Otros",
        pricingTag: "Precios",
        pricingTitle: "Elige tu plan",
        pricingSubtitle: "Comienza gratis. Actualiza cuando quieras.",
        faqTag: "FAQ",
        faqTitle: "Preguntas frecuentes",
        finalCtaTitle: "¿Listo para dejar de procrastinar?",
        finalCtaSubtitle: "Únete a {count}+ personas esperando ContextFlow",
        finalCtaBenefits: "✓ Acceso anticipado febrero 2026 • ✓ 50% descuento de por vida • ✓ Sin tarjeta requerida",
        copyright: "© 2026 ContextFlow. Todos los derechos reservados."
    }
};
